services:
  traefik:
    image: traefik:v3.5.3
    container_name: propertea-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - propertea-network
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=propertea-network
      - --providers.file.watch=true
      - --providers.file.directory=/etc/traefik/dynamic
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --serversTransport.insecureSkipVerify=true
    ports:
      - "80:80" # http
      - "443:443" # https
      - "8080:8080" # http api dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik/dynamic:ro
      - ./certs:/etc/traefik/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.propertea.dev`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
  
  postgres:
    image: postgres:18-alpine
    container_name: propertea-postgres
    environment:
      POSTGRES_DB: propertea
      POSTGRES_USER: propertea
      POSTGRES_PASSWORD: dev-password-change-in-prod
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - propertea-postgres-data:/var/lib/postgresql
      - propertea-postgres-data:/docker-entrypoint-initdb.d
    networks:
      - propertea-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U propertea -d propertea"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
networks:
  propertea-network:
    driver: bridge
    
volumes:
  propertea-postgres-data: