include:
    - docker-compose.infrastructure.yml    
    - docker-compose.observability.yml

services:
  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/ProperTea.Gateway/Dockerfile
    container_name: propertea-gateway
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:80
    networks:
      - propertea-network
    depends_on:
      - postgres
      - redis
      - kafka
      - azurite
      - opensearch      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`gateway.local.test`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls=true"
      - "traefik.http.services.gateway.loadbalancer.server.port=5000"

