include:
  - docker-compose.shared.yml
  - docker-compose.infrastructure.yml
  - docker-compose.observability.yml

services:        
  identity:
    build:
      context: .
      dockerfile: services/identity/ProperTea.Identity.Service/Dockerfile
    container_name: propertea-identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=propertea_identity;Username=propertea;Password=dev-password-change-in-prod
    ports:
      - "5000:80"
    networks:
      - propertea-network
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity.rule=Host(`identity.propertea.dev`)"
      - "traefik.http.routers.identity.entrypoints=websecure"
      - "traefik.http.routers.identity.tls=true"

networks:
  propertea-network:
    driver: bridge
    name: propertea-network