include:
  - docker-compose.shared.yml
  - docker-compose.infrastructure.yml
  - docker-compose.observability.yml
      
services:
  gateway:
    build:
      context: .
      dockerfile: services/gateway/ProperTea.Gateway/Dockerfile
    container_name: propertea-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - propertea-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`gateway.propertea.dev`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls=true"

networks:
  propertea-network:
    driver: bridge
    name: propertea-network