services:
  loki:
    image: grafana/loki:3.5.5
    container_name: propertea-loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki-config.yaml:/etc/loki/local-config.yaml
      - propertea-loki-data:/loki
    networks:
      - propertea-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.propertea.dev`)"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.tls=true"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
  
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: propertea-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-otlp-receiver
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
      - propertea-prometheus-data:/prometheus
    networks:
      - propertea-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.propertea.dev`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"        
  
  jaeger:
    image: jaegertracing/jaeger:2.10.0
    container_name: propertea-jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"  # Jaeger UI
    volumes:
      - propertea-jaeger-data:/tmp
    networks:
      - propertea-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.propertea.dev`)"
      - "traefik.http.routers.jaeger.entrypoints=websecure"
      - "traefik.http.routers.jaeger.tls=true"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"  
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.135.0
    container_name: propertea-otel-collector
    restart: unless-stopped
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "8889:8889"
      - "55679:55679" # zPages extension
    networks:
      - propertea-network
    depends_on:
      - prometheus
      - jaeger
      - loki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zpages.rule=Host(`zpages.propertea.dev`)"
      - "traefik.http.routers.zpages.entrypoints=websecure"
      - "traefik.http.routers.zpages.tls=true"
      - "traefik.http.services.zpages.loadbalancer.server.port=55679"
  
  # Grafana - Metrics Visualization
  grafana:
    image: grafana/grafana:12.2.0
    container_name: propertea-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    volumes:
      - propertea-grafana-data:/var/lib/grafana
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - propertea-network
    depends_on:
      - prometheus
      - jaeger
      - loki
      - otel-collector
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.propertea.dev`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

volumes:
  propertea-jaeger-data:
  propertea-prometheus-data:
  propertea-loki-data:
  propertea-grafana-data: