tls:
  certificates:
    - certFile: /etc/traefik/certs/_wildcard.local.test.pem
      keyFile: /etc/traefik/certs/_wildcard.local.test-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/_wildcard.local.test.pem
        keyFile: /etc/traefik/certs/_wildcard.local.test-key.pem
