namespace ProperTea.Property.Features.Buildings;

#pragma warning disable CA1707
public static class BuildingErrorCodes
{
    public const string BUILDING_NOT_FOUND = "BUILDING_NOT_FOUND";
    public const string BUILDING_NAME_REQUIRED = "BUILDING_NAME_REQUIRED";
    public const string BUILDING_CODE_REQUIRED = "BUILDING_CODE_REQUIRED";
    public const string BUILDING_CODE_TOO_LONG = "BUILDING_CODE_TOO_LONG";
    public const string BUILDING_CODE_INVALID_FORMAT = "BUILDING_CODE_INVALID_FORMAT";
    public const string BUILDING_CODE_ALREADY_EXISTS = "BUILDING_CODE_ALREADY_EXISTS";
    public const string BUILDING_ALREADY_DELETED = "BUILDING_ALREADY_DELETED";
    public const string BUILDING_PROPERTY_REQUIRED = "BUILDING_PROPERTY_REQUIRED";
    public const string BUILDING_ADDRESS_REQUIRED = "BUILDING_ADDRESS_REQUIRED";
    public const string BUILDING_ENTRANCE_NOT_FOUND = "BUILDING_ENTRANCE_NOT_FOUND";
    public const string BUILDING_ENTRANCE_CODE_REQUIRED = "BUILDING_ENTRANCE_CODE_REQUIRED";
    public const string BUILDING_ENTRANCE_CODE_TOO_LONG = "BUILDING_ENTRANCE_CODE_TOO_LONG";
    public const string BUILDING_ENTRANCE_CODE_INVALID_FORMAT = "BUILDING_ENTRANCE_CODE_INVALID_FORMAT";
    public const string BUILDING_ENTRANCE_CODE_ALREADY_EXISTS = "BUILDING_ENTRANCE_CODE_ALREADY_EXISTS";
    public const string BUILDING_ENTRANCE_NAME_REQUIRED = "BUILDING_ENTRANCE_NAME_REQUIRED";
    public const string BUILDING_HAS_ACTIVE_UNITS = "BUILDING_HAS_ACTIVE_UNITS";
    public const string BUILDING_ENTRANCE_HAS_ACTIVE_UNITS = "BUILDING_ENTRANCE_HAS_ACTIVE_UNITS";
}
#pragma warning restore CA1707
