// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheSupremacy.ProperSagas.Persistence.Ef.IntegrationTests;

#nullable disable

namespace TheSupremacy.ProperSagas.Persistence.Ef.IntegrationTests.Migrations
{
    [DbContext(typeof(SagaDbContext))]
    [Migration("20251111034135_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheSupremacy.ProperSagas.Persistence.Ef.SagaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsCancellationRequested")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SagaData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SagaType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeoutDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SagaType");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "LockedAt");

                    b.HasIndex("Status", "TimeoutDeadline");

                    b.ToTable("Sagas");
                });
#pragma warning restore 612, 618
        }
    }
}
