services:
  api-gateway:
     build:
       context: .
       dockerfile: ProperTea.ApiGateway/Dockerfile
     container_name: propertea-api-gateway
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=https://http://+:80
     networks:
       - propertea-network
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.gateway.rule=Host(`api-gateway.propertea.dev`)"
       - "traefik.http.routers.gateway.entrypoints=websecure"
       - "traefik.http.routers.gateway.tls=true"

networks:
  propertea-network: