apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://prometheus.propertea.dev
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: https://loki.propertea.dev
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:43177
    editable: true