tls:
  certificates:
    - certFile: /etc/traefik/certs/_wildcard.dev.pem
      keyFile: /etc/traefik/certs/_wildcard.dev-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/_wildcard.dev.pem
        keyFile: /etc/traefik/certs/_wildcard.dev-key.pem