global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['localhost:55680']  # OTLP HTTP port
        
  - job_name: 'loki'
    static_configs:
      - targets: [ 'localhost:3100' ]